<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EditarProductos.aspx.cs" Inherits="Vistas.EliminarProducto" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="icon" type="image/png" href="img/icono.png" />
    <link rel="styleSheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css" />
    <link href="Style.css" rel="StyleSheet" type="text/css" />
    <script src="https://kit.fontawesome.com/0440de58e7.js" crossorigin="anonymous"></script>
    <title>La Divina Comidad | Iniciar Sesión</title>
    <style type="text/css">
        .Contenedor-G {
            display: flex;
            justify-content: space-around;
            align-items: center;
            flex-direction: column;
        }
        .Contenedor-Gridview {
            text-align: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            margin: 10px;
        }   
        .blancoa {
            margin-top: 21%;
        }
    </style>
</head>

<body>
    <form id="form1" runat="server">
        <header class="header">
            <div class="logo">
                <a href="AgregarProducto.aspx">
                    <img class="logo_img" src="img/logo.png" />
                </a>
            </div>
            <div class="menu">
                <asp:HyperLink ID="hlAgregarProducto" runat="server" NavigateUrl="~/AgregarProducto.aspx" class="link">Agregar Producto</asp:HyperLink>
                <asp:HyperLink ID="hlEditarProducto" runat="server" NavigateUrl="~/EditarProductos.aspx" class="link">Editar/Eliminar Producto</asp:HyperLink>
                <asp:HyperLink ID="hlPedidos" runat="server" NavigateUrl="~/Pedidos.aspx" class="link">Pedidos</asp:HyperLink>
                <asp:HyperLink ID="hlReportes" runat="server" NavigateUrl="~/Reporte.aspx" class="link">Reporte</asp:HyperLink>
                <asp:HyperLink ID="hlCuentas" runat="server" NavigateUrl="~/Cuentas.aspx" class="link">Cuentas</asp:HyperLink>
                <asp:HyperLink ID="hlCerrarSesion" runat="server" class="link" NavigateUrl="~/IniciarSesion.aspx">Cerrar Sesión</asp:HyperLink>
            </div>
        </header>
        <main class="Contenedor-G">
                    <h1 style="text-align: center">Editar o eliminar
                        Productos</h1>
        <p style="text-align: center">
            <asp:TextBox ID="TxtBuscarProg" runat="server"></asp:TextBox>
&nbsp;&nbsp;&nbsp;
            <asp:Button ID="BtnBuscarProducto" runat="server" OnClick="BtnBuscarProducto_Click" Text="buscar" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="BtnLimpiar" runat="server" OnClick="BtnLimpiar_Click" Text="Limpiar" />
        </p>
                    <div class="Contenedor-Gridview">
                            <asp:GridView ID="GrdListarProductos" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical" OnRowCancelingEdit="GridListarProductos_RowCancelingEdit" OnRowDeleting="GrdListarProductos_RowDeleting" OnRowEditing="GridListarProductos_RowEditing" OnRowUpdating="GridListarProductos_RowUpdating" OnRowDataBound="GrdListarProductos_RowDataBound" AllowPaging="True" OnPageIndexChanging="GrdListarProductos_PageIndexChanging" PageSize="15">
                                <AlternatingRowStyle BackColor="#CCCCCC" />
                                <Columns>
                                    <asp:TemplateField HeaderText="Codigo producto">
                                        <EditItemTemplate>
                                            <asp:Label ID="Lbl_Eit_CodProducto" runat="server" Text='<%# Bind("CodProducto_Pr") %>'></asp:Label>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Lbl_it_CodProducto" runat="server" Text='<%# Bind("CodProducto_Pr") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Codigo Categoria">
                                        <EditItemTemplate>
                                            <asp:DropDownList ID="Ddl_eit_CodCategoria" runat="server">
                                            </asp:DropDownList>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Lbl_it_CodCategoria" runat="server" Text='<%# Bind("CodCategoria_Ct_Pr") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Codigo Tipo Producto">
                                        <EditItemTemplate>
                                            <asp:DropDownList ID="Ddl_eit_TipoProducto" runat="server">
                                            </asp:DropDownList>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Lbl_it_CodTipoProducto" runat="server" Text='<%# Bind("CodTipoProducto_T_Pr") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Stock">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="Txt_eit_StockProducto" runat="server" Text='<%# Bind("stock_Pr") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Lbl_it_StockProducto" runat="server" Text='<%# Bind("stock_Pr") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Nombre Producto">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="Txt_eit_NombreProducto" runat="server" Text='<%# Bind("NombreProducto_Pr") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Lbl_it_NombreProducto" runat="server" Text='<%# Bind("NombreProducto_Pr") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Descripcion">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="Txt_Eit_Descripcion" runat="server" Text='<%# Bind("Descripcion_Pr") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Lbl_it_Descripcion" runat="server" Text='<%# Bind("Descripcion_Pr") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="PrecioUnitario">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="Txt_eit_PrecioUnitario" runat="server" Text='<%# Bind("PrecioUnitario_Pr") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Lbl_it_PrecioUnitario" runat="server" Text='<%# Bind("PrecioUnitario_Pr") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="URL imagen">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="Txt_eit_imagen" runat="server" Text='<%# Bind("ImagenURL_Pr") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Lbl_it_imagenProducto" runat="server" Text='<%# Bind("ImagenURL_Pr") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Activo">
                                        <EditItemTemplate>
                                            <asp:TextBox ID="Txt_eit_EstadoProducto" runat="server" Text='<%# Bind("Estado_Pr") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Lbl_it_EstadoProducto" runat="server" Text='<%# Bind("Estado_Pr") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                </Columns>
                                <FooterStyle BackColor="#CCCCCC" />
                                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                                <SortedAscendingHeaderStyle BackColor="#808080" />
                                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                                <SortedDescendingHeaderStyle BackColor="#383838" />
                            </asp:GridView>
                            <br />
                    </div>
        </main>
        <div class="blancoa">

            </div>
        <footer class="footer" id="foter">
                    <div class="grupo-2">
                        <small>&copy; 2023 <b>La Divina Comida</b> - Todos los Derechos Reservados.</small>
                    </div>
                </footer>
    </form>
</body>
</html>
